spring:
  profiles:
    active: pro
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8080
  session:
    timeout: 1800

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000

api-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 10000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000
  maxAutoRetries: 0
  maxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true

zuul:
  retryable: true
  routes:
    api-service:
      path: /api_service/**
      service-id: api-service
    menu-api:
      path: /blog_service/**
      service-id: blog-service
    import-export-service:
      path: /excel_service/**
      service-id: excel-service