#spring配置
spring:
  application:
    name: process-service #服务名
  profiles: #环境配置
    active: dev #开发环境:dev 生产环境:pro
  activiti: #activiti配置
    check-process-definitions: false
    history-level: activity

server:
  port: 8081 #服务端口

#eureka服务配置
eureka:
  instance: #服务实例
    instance-id: ${spring.application.name}:${server.port} #服务实例名称
    prefer-ip-address: true #不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    lease-renewal-interval-in-seconds: 10 #服务续约任务的调用时间，默认为30秒
    lease-expiration-duration-in-seconds: 60 #服务失效时间，默认为90秒
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#数据库配置，阿里druid连接池
mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/xlbs_activity_dev?useAffectedRows=true&useSSL=false
    username: root
    password: xlbs.com